# Generated by Django 6.1.1 on 2026-09-29 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('resumen', models.CharField(max_length=200)),
                ('detalle', models.TextField()),
            ],
            options={
                'db_table': 'gestoria_servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_empresa', models.CharField(max_length=150)),
                ('cliente_rut', models.CharField(max_length=12)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('servicio_nombre', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(default='nuevo', max_length=20)),
                ('fecha', models.DateField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='gestoria.serviciomodel')),
            ],
            options={
                'db_table': 'gestoria_solicitudes',
                'ordering': ['-id'],
            },
        ),
    ]
